#%RAML 1.0
title: DrQMuller v3.0
baseUri: http://localhost:5000
version:
securitySchemes:
  x-token:
    description: |
      A custom security scheme for authenticating requests.
    type: x-custom
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a custom token.
          type: string
          example: bc5990f1-fb92-4715-a831-ee073a4bc3f5
      responses:
        200:
          body:
            application/json:
          description: Successful request
        401:
          description: |
            Bad token.

types:
  Name:
    type: string
    pattern: ^[${finnish}\\-.\\s']{0,50}$
  Address:
    type: string
    pattern: ^[${A-Za-zäöÄÖåÅéÉüÜ0-9}][${A-Za-zäöÄÖåÅéÉüÜ0-9}\\-.,\\/\\s'"]{0,48}[${A-Za-zäöÄÖåÅéÉüÜ0-9}]$
  NameAddress:
    type: object
    properties:
      name: Name
      address: Address
  Gender:
    type: string
    pattern: ^(?:Male|Female)$
  Dob:
    type: string
    pattern: ^(19|20)\d\d[- \/.](0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])
  GenderDob:
    type: object
    properties:
      gender: Gender
      dob: Dob
  Email:
    type: string
    pattern: ^[-!#$%&'*+\/0-9=?A-Z^_a-z{|}~](\.?[-!#$%&'*+\/0-9=?A-Z^_a-z\`{|}~])*@[a-zA-Z0-9](-?\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$
  Phone:
    type: string
    pattern: ^\+?[0-9]+[0-9\-\s]+\\?([0-9]+\\)?[0-9\-\s]+[0-9]$
  EmailPhone:
    type: object
    properties:
      email: Email
      phone: Phone
  UserInformation:
    type: object
    properties:
      NameAndAddress: NameAddress
      GenderAndDob: GenderDob
      EmailAndPhone: EmailPhone

/signin:
  post:
    description: User signin
    body:
      application/json:
        example: |
          {
            "username": "username1",
            "password": "password1"
          }
    responses:
      200:
        body:
          application/json:
            example: |
             {
               "loginToken": "53292990-3645-11e8-af05-bd47a7e93b38"
             }
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "Invalid username or password",
               "error_code": "invalid_username_or_password"
             }

/signout:
  securedBy: x-token
  post:
    description: User signout
    responses:
      200:
        body:
          text:
            type: EmptyString
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}

/user:
  post:
    description: Create new user
    body:
      application/json:
        example: |
          {
            "username": "username1",
            "password": "password1"
          }
    responses:
      201:
        body:
          application/json:
            example: |
             {
               "loginToken": "53292990-3645-11e8-af05-bd47a7e93b38"
             }
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }

/user/me:
  securedBy: x-token
  put:
    description: Update user information
    body:
      application/json:
        example: |
          {
            "name": "Santa Clause",
            "address": "Lapland"
          }
          or
          {
            "gender": "Male",
            "dob": "1980/11/11"
          }
          or
          {
            "email": "santa.clause@lapland.com",
            "phone": "0987654321"
          }
        type: UserInformation
    responses:
      200:
        body:
          application/json:
            example: |
             {}
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}
