#%RAML 1.0
title: DrQMuller v3.0
baseUri: https://localhost:5000
version:
securitySchemes:
  x-token:
    description: |
      A custom security scheme for authenticating requests.
    type: x-custom
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a custom token.
          type: string
          example: bc5990f1-fb92-4715-a831-ee073a4bc3f5
      responses:
        200:
          body:
            application/json:
          description: Successful request
        401:
          description: |
            Bad token.

types:
  Name:
    type: string
    pattern: ^[${finnish}\\-.\\s']{0,50}$
  Address:
    type: string
    pattern: ^[${A-Za-zäöÄÖåÅéÉüÜ0-9}][${A-Za-zäöÄÖåÅéÉüÜ0-9}\\-.,\\/\\s'"]{0,48}[${A-Za-zäöÄÖåÅéÉüÜ0-9}]$
  NameAddress:
    type: object
    properties:
      name: Name
      address: Address
  Gender:
    type: string
    pattern: ^(?:Male|Female)$
  Dob:
    type: string
    pattern: ^(19|20)\d\d[- \/.](0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])
  GenderDob:
    type: object
    properties:
      gender: Gender
      dob: Dob
  Email:
    type: string
    pattern: ^[-!#$%&'*+\/0-9=?A-Z^_a-z{|}~](\.?[-!#$%&'*+\/0-9=?A-Z^_a-z\`{|}~])*@[a-zA-Z0-9](-?\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$
  Phone:
    type: string
    pattern: ^\+?[0-9]+[0-9\-\s]+\\?([0-9]+\\)?[0-9\-\s]+[0-9]$
  EmailPhone:
    type: object
    properties:
      email: Email
      phone: Phone
  UserInformation:
    type: object
    properties:
      NameAndAddress: NameAddress
      GenderAndDob: GenderDob
      EmailAndPhone: EmailPhone
  UUID:
    type: string
    pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
  Date:
    type: string
    pattern: ^\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$
  Time:
    type: string
    pattern: ^([0-1][0-9]|[2][0-2]):[0-5][0-9]$
  Schedule:
    type: object
    properties:
      date: Date
      time: Time
  NewAppointment:
    type: object
    properties:
      machineId: UUID
      schedule: Schedule

/availableTime:
  securedBy: x-token
  get:
    description: Retrieve available time for appointment booking
    queryParameters:
      date: Date
      machineId: UUID
    responses:
      200:
        body:
          application/json:
            example: |
             [
               "06:00",
               "06:15",
               "06:45",
               "07:15",
               "07:30",
               "07:45",
             ]
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}

/appointments:
  securedBy: x-token
  get:
    description: Get all user appointments
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "53292990-3645-11e8-af05-bd47a7e93b38",
                  "userId": "A0DF70F5-8209-410D-A647-814199A278D5",
                  "machineId": "9DCFE033-DDE6-4B87-BBFE-46204528CA9E",
                  "schedule": {
                    "date": "2030-12-12",
                    "time": "12:00"
                  },
                  "updatedAt": "2018-04-09T10:07:35+03:00",
                  "createdAt": "2018-04-09T10:07:35+03:00"
                }
              ]
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}

/machines:
  securedBy: x-token
  get:
    description: Get all machines
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                    "id": "F0FFDCA9-5674-4D58-913E-DABDEF83DF55",
                    "name": "Dr. Müller Beauty Light Therapy"
                },
                {
                    "id": "C42F0761-DF21-4DD6-BBC2-1FB698A0660B",
                    "name": "Dr. Müller Changing Cubicle"
                }
              ]
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}

/signin:
  post:
    description: User signin
    body:
      application/json:
        example: |
          {
            "username": "username1",
            "password": "password1"
          }
    responses:
      200:
        body:
          application/json:
            example: |
             {
               "loginToken": "53292990-3645-11e8-af05-bd47a7e93b38"
             }
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "Invalid username or password",
               "error_code": "invalid_username_or_password"
             }

/signout:
  securedBy: x-token
  post:
    description: User signout
    responses:
      200:
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}

/user:
  post:
    description: Create new user
    body:
      application/json:
        example: |
          {
            "username": "username1",
            "password": "password1"
          }
    responses:
      201:
        body:
          application/json:
            example: |
             {
               "loginToken": "53292990-3645-11e8-af05-bd47a7e93b38"
             }
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }

/resetPasswordRequest:
  post:
    description: Send reset password request
    body:
      application/json:
        example: |
          {
            "email": "santa.clause@lapland.com"
          }
    responses:
      200:
        body:
          application/json:
            example: |
             {}
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }

/appointment:
  securedBy: x-token
  post:
    description: Create new appointment
    body:
      application/json:
        example: |
          {
            "machineId": "158033AE-1B43-4FF0-B2AE-F9D58170127B",
            "schedule": {
              "date": "2030-12-12",
              "time": "18:00"
            }
          }
        type: NewAppointment
    responses:
      201:
        body:
          application/json:
            example: |
             {}
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}
  patch:
    description: Cancel appointment
    body:
      application/json:
        example: |
          {
            "appointmentId": "158033AE-1B43-4FF0-B2AE-F9D58170127B"
          }
    responses:
      200:
        body:
          application/json:
            example: |
             {}
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}

/resetPasswordConfirm:
  securedBy: x-token
  patch:
    description: Reset password
    body:
      application/json:
        example: |
          {
            "token": "158033AE-1B43-4FF0-B2AE-F9D58170127B",
            "password": "newpassword1234"
          }
    responses:
      200:
        body:
          application/json:
            example: |
             {}
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
             or
             {
                "error_message": "Token has already been expired",
                "error_code": "token_expired"
             }

/user/me:
  securedBy: x-token
  patch:
    description: Update user information
    body:
      application/json:
        example: |
          {
            "name": "Santa Clause",
            "address": "Lapland"
          }
          or
          {
            "gender": "Male",
            "dob": "1980/11/11"
          }
          or
          {
            "email": "santa.clause@lapland.com",
            "phone": "0987654321"
          }
        type: UserInformation
    responses:
      200:
        body:
          application/json:
            example: |
             {}
      400:
        body:
          application/json:
            example: |
             {
               "error_message": "There was a server error",
               "error_code": "server_error"
             }
      401:
        body:
          application/json:
            example: |
             {}
